### ISSUE TITLE
Getting started instructions

### ISSUE THREAD

**Issue by nojaf** [Nsidorenco/tree-sitter-fsharp#1]
Hello, I'm following the thread at https://github.com/dotnet/fsharp/issues/14527.
Very cool to see that somebody is working on this.

I think it would be beneficial to have a "getting started" file in this repository.
How can people play around with this? How can they contribute? How do I run the tests?
More contributors could be drawn in if this information was easily accessible.

**Comment by Nsidorenco** [comment]
Hi @nojaf,
Thank you for commenting, I think what your suggesting sounds like a good idea!
I will try and get something along the lines of a getting started section once I get the time.
