### ISSUE TITLE
Parser gives errors for parenthesised expressions, or unit

### ISSUE THREAD

**Issue by marklam** [Nsidorenco/tree-sitter-fsharp#10]
Sorry - I'm not sure what the expected output should be, so I haven't tried to add these to the corpus.

But `x`, `y` and `z` here cause errors:
```f#
module T
let x a = (a)
let y = Choice1Of2 ("hi")
let z = ()
```

I suspect that `z` being `unit` might be a different problem to `x` and `y`?

**Comment by marklam** [comment]
I'll have a go (time permitting).

**Comment by marklam** [comment]
@Nsidorenco I think I need a hint.

 It looks like the `function_or_value_defn` isn't getting a `function_or_value_defn_body` because its `expression` isn't matching a `paren_expression` .

The definition looks believable to me, unless it's something to do with the mysterious `_virtual_open_section` and `_virtual_close_section`.

**Comment by Nsidorenco** [comment]
Really cool you’re giving this a go @marklam!
If you run `npm run debug $file` on the example you can see when the parser consumes a token and which node it generates from it, this usually helps me. 

I suspect that the parser is getting in a bad state for one of the following reasons:
- The precedence of the paren expression is too low
- The parser believe it has parsed an expression node before consuming the “)”. 
- An _virtual_open_section is inserted after the “(“ has been consumed.

**Comment by marklam** [comment]
Things I'm fairly`*` sure don't fix it:
1. Removing the block comment parsing from scanner.cc
2. Removing the block comment matching from grammar.js
3. Removing the `_virtual_open_section` and `_virtual_end_section` from `paren_expression`
4. A higher numeric precedence for paren_expression
5. A lower numeric precedence for paren_expression

`*` I got very frustrated with the tooling not seeming to reliably rebuild the executables, and the fact that all I had to go on was numeric parser states that don't always seem to directly relate to any of the names from grammar.js.

I think I might have to surrender on this one.

**Comment by Nsidorenco** [comment]
@marklam thank you for giving this a shot.
I agree that the tooling for debugging the parsing is not that easy to use, unfortunately I am not familiar with a better way.

I managed to get you example working when I was playing around with the tokens from the external parser used in `application_expression` and `sequence_expression` in commit f6c1a1425c89747363dbbc7f7802e23e8af9e908.
So it was likely an issues with the `$._virtual_open_section` tokens.

Thank you for the help!
