### ISSUE TITLE
What F# spec is this based on?

### ISSUE THREAD

**Issue by Eliemer** [Nsidorenco/tree-sitter-fsharp#12]
Im curious what version of the spec is being referenced for the grammar. F# doesnt change much to be fair, but it'd be a nice detail to include in the README along with a link to the particular one being used.

https://fsharp.org/specs/language-spec/

**Comment by Nsidorenco** [comment]
It's largely based on 4.1 specification of the language. It has, however, deviated a bit in my attempts to get the grammar into a working state.
But I agree it would be good to add some more information to the README on where to find reference material on the grammar :)
