### ISSUE TITLE
Can't parse most files

### ISSUE THREAD

**Issue by aryx** [Nsidorenco/tree-sitter-fsharp#33]
Hi,

I'm trying to use your parser for adding support for F# in semgrep, but
when running parsing statistics on the top 30 F# projects on github, the parser can't parse most files ...
Even many of the example in https://en.wikipedia.org/wiki/F_Sharp_(programming_language)#Examples
do not parse; For example hello.fs (hello world) does not parse and generate tree-sitter errors.

Is it normal? Do I need to configure something special when calling tree-sitter?

**Comment by aryx** [comment]
One issue I think is because you do not allow toplevel expression outside of a do.

**Comment by aryx** [comment]
Another issue is that it's the only tree-sitter grammar.js I've seen where the comments are not parts of the extras: field.
They should because comments in theory can happen anywhere, so you definitely want to skip them by adding them
in the extras: field.

**Comment by aryx** [comment]
On the stats I ran of the top-30 F# projects on github I get:
```
Line count: 1096149
Line coverage: 12.211%
```

**Comment by aryx** [comment]
Meaning it was able to parse only 12% of the 1.09M LOC

**Comment by vzarytovskii** [comment]
That's pretty much expected, parser is still very much WIP.

**Comment by vzarytovskii** [comment]
> Did you consider the changes I proposed above? put the comment regexp in extras: and allow toplevel expressions? that should significantly improve the stats I think.

I'm not maintaner of the parser, but I think it will be a welcommed change, if it parses valid F# code correctly.

**Comment by Nsidorenco** [comment]
> Did you consider the changes I proposed above? put the comment regexp in extras: and allow toplevel expressions?
> that should significantly improve the stats I think.

Putting comment regex in the extras in not an "easy fix". String literals can contain comment delimiters, which should be parsed a the body of the literal string. They indeed used to be part of the extras, but ultimately, we will have to think of a better way.

I'll close this issues since it is very much expected that you won't be able to parse most files given the current state of the parser.

**Comment by aryx** [comment]
String literals can contain comment delimiters in every languages, not just in F#, and every other tree-sitter languages put the comments in the extras: section.

**Comment by aryx** [comment]
I don't understand why you're closing this issue. Don't you want your parser to parse most files? Don't you think we should address this issue and find techniques to solve this issue (like the 2 I mentioned above about toplevel exprs and comments in extras).

**Comment by aryx** [comment]
Just to be clear, I think the current grammar is pretty good and that with very little effort we could manage to parse 90% of the files! (instead of the current 12%).

**Comment by vzarytovskii** [comment]
> I don't understand why you're closing this issue. Don't you want your parser to parse most files? Don't you think we should address this issue and find techniques to solve this issue (like the 2 I mentioned above about toplevel exprs and comments in extras).
> 
> 

I personally think ghis issue is not very actionable, it can serve as discussion, but issues should cover a very specific problem/suggestion, so it can be picked up by someone to fix it.
