### ISSUE TITLE
Syntax highlighting still disabled

### ISSUE THREAD

**Issue by ChristophSchmidpeter** [Nsidorenco/tree-sitter-fsharp#34]
The repository already has ha [highlights.scm](https://github.com/Nsidorenco/tree-sitter-fsharp/blob/develop/queries/highlights.scm) file, but the highlighings are still disabled.

Steps to reproduce:
* Follow the instructions in the [Adding to neovim](https://github.com/Nsidorenco/tree-sitter-fsharp/tree/develop?tab=readme-ov-file#adding-to-neovim) section
* Execute in neovim `:TSInstallFromGrammar fsharp`
* `:TSModuleInfo` shows an 'x' instead of a checkmark for 'fsharp' and 'highlights'

**Comment by Nsidorenco** [comment]
Hi,

This is an artefact of how the Neovim tree sitter integration works. Neovim won't import the highlights from the parser repository. So there is not much that can be done about this.
